import type { ProductList } from "@/lib/types";

export const dronesMaio2026: ProductList = {
  slug: "10-melhores-drones-maio-2026",
  title: "Os 10 Melhores Drones (Maio 2026)",
  category: "Drones",
  monthYear: "Maio de 2026",
  metaDescription:
    "Comparativo dos 10 melhores drones disponíveis em maio de 2026 no Brasil. Análise de câmera, autonomia, alcance e preço, com links direto para Amazon e Mercado Livre.",
  publishedAt: "2026-05-09",
  updatedAt: "2026-05-09",
  intro:
    "Escolher um drone em 2026 ficou ao mesmo tempo mais simples e mais confuso. Simples porque a qualidade média subiu — até modelos de entrada filmam em 4K, voam por mais de 25 minutos e cabem na palma da mão. Confuso porque a quantidade de variações cresceu na mesma proporção: drones com câmera estabilizada, com sensores de obstáculo, com transmissão de longo alcance, FPV, sub-250g (que dispensam registro na ANAC para uso recreativo), e por aí vai.\n\nPara essa lista comparamos modelos disponíveis no Brasil em maio de 2026, considerando qualidade de imagem, estabilidade em vento, autonomia real (não a do papel), distância de transmissão segura, facilidade de uso e custo-benefício. Cada drone tem prós e contras explícitos — não existe \"melhor para todo mundo\", existe melhor para o seu uso.",
  conclusion:
    "Se você nunca pilotou um drone, comece por um modelo sub-250g — você não precisa registrar na ANAC para uso recreativo, é mais perdoável em rajada de vento e tem curva de aprendizado mais suave. Se você é criador de conteúdo e quer qualidade profissional, o salto para os modelos com sensor 1\" vale o investimento. Para piloto FPV ou esporte, modelos dedicados continuam sendo a única opção razoável — drones de fotografia não substituem a agilidade necessária.",
  faq: [
    {
      question: "Preciso registrar meu drone na ANAC?",
      answer:
        "Drones acima de 250g precisam de cadastro no SISANT (sistema da ANAC), que é gratuito e online. Drones com até 250g (incluindo a bateria) usados de forma recreativa estão dispensados do cadastro, mas ainda devem respeitar as regras de espaço aéreo do DECEA.",
    },
    {
      question: "Posso voar em qualquer lugar?",
      answer:
        "Não. É proibido voar próximo a aeroportos, áreas de segurança nacional, presídios e em condições meteorológicas adversas. Para voos sobre pessoas, em áreas urbanas ou acima de 120m de altura, há regras específicas — consulte o app DroneZone do DECEA.",
    },
    {
      question: "Qual a diferença entre drone com câmera e drone FPV?",
      answer:
        "Drones com câmera (estilo DJI Mavic) priorizam estabilidade, foto e vídeo cinematográfico, e voam por GPS — bom para iniciantes e criadores de conteúdo. Drones FPV (First Person View) são pilotados via óculos com transmissão em tempo real, focam em agilidade e manobras, e exigem mais habilidade.",
    },
  ],
  products: [
    {
      rank: 1,
      name: "Placeholder Drone #1",
      tagline: "O melhor custo-benefício geral",
      description:
        "Placeholder — vamos preencher com o drone real depois de pesquisar via Amazon Associados e Mercado Livre Afiliados. Este texto será substituído pela análise editorial completa do produto, explicando por que ele lidera a lista, em que situações brilha e quais limitações existem.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: [
        "Câmera 4K com gimbal de 3 eixos",
        "Autonomia real de ~30 minutos",
        "Sub-250g — dispensa cadastro ANAC",
      ],
      cons: ["Sem sensores anti-colisão", "Vento forte limita estabilidade"],
      rating: 4.7,
      reviewCount: 1200,
    },
    {
      rank: 2,
      name: "Placeholder Drone #2",
      tagline: "Melhor para criadores de conteúdo",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Sensor 1\" maior", "Transmissão de longo alcance"],
      cons: ["Preço mais alto", "Acima de 250g — precisa cadastro"],
      rating: 4.8,
      reviewCount: 850,
    },
    {
      rank: 3,
      name: "Placeholder Drone #3",
      tagline: "Melhor entrada para iniciantes",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Fácil de pilotar", "Preço acessível"],
      cons: ["Câmera mais simples", "Autonomia menor"],
      rating: 4.5,
      reviewCount: 2400,
    },
    {
      rank: 4,
      name: "Placeholder Drone #4",
      tagline: "Melhor drone FPV pronto pra voar",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Experiência imersiva", "Velocidade alta"],
      cons: ["Curva de aprendizado íngreme", "Não é para foto/vídeo cinematográfico"],
      rating: 4.6,
      reviewCount: 320,
    },
    {
      rank: 5,
      name: "Placeholder Drone #5",
      tagline: "Melhor para viagem (compacto)",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Dobrável, cabe na bolsa", "Bom equilíbrio peso/qualidade"],
      cons: ["Sem zoom óptico", "Microfone fraco"],
      rating: 4.6,
      reviewCount: 670,
    },
    {
      rank: 6,
      name: "Placeholder Drone #6",
      tagline: "Melhor zoom e alcance",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Zoom híbrido", "Alcance superior a 10km"],
      cons: ["Pesado", "Drone grande, chama atenção"],
      rating: 4.7,
      reviewCount: 410,
    },
    {
      rank: 7,
      name: "Placeholder Drone #7",
      tagline: "Melhor drone sob R$ 1.500",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Preço justo", "Boa qualidade de imagem para o segmento"],
      cons: ["Sem retorno automático em alguns casos", "Bateria extra cara"],
      rating: 4.4,
      reviewCount: 1900,
    },
    {
      rank: 8,
      name: "Placeholder Drone #8",
      tagline: "Melhor drone para crianças (educativo)",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Robusto a quedas", "Programação visual incluída"],
      cons: ["Câmera só para diversão", "Alcance curto"],
      rating: 4.3,
      reviewCount: 540,
    },
    {
      rank: 9,
      name: "Placeholder Drone #9",
      tagline: "Melhor drone com sensores anti-colisão completos",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Detecção em todas as direções", "Modos automáticos avançados"],
      cons: ["Premium", "Excesso de funções para iniciante"],
      rating: 4.8,
      reviewCount: 290,
    },
    {
      rank: 10,
      name: "Placeholder Drone #10",
      tagline: "Melhor drone profissional cinema",
      description: "Placeholder — análise virá aqui.",
      imageUrl: "/placeholder-product.svg",
      amazonAsin: "B000000000",
      mercadoLivreUrl: "https://mercadolivre.com/sec/PLACEHOLDER",
      pros: ["Câmera com sensor M4/3", "ProRes RAW"],
      cons: ["Caro", "Curva de uso profissional"],
      rating: 4.9,
      reviewCount: 110,
    },
  ],
};
